[project]
name = "realtime-audio-quickstart"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "azure-identity>=1.19.0",
    "python-dotenv>=1.0.1",
]

[tool.uv.sources]
src = { workspace = true }
